### ISSUE TITLE
[Question] Is sourcegraph app currently limit local repo?

### ISSUE THREAD

**Issue by haunt98** [sourcegraph/app#1]
I have ~ 50 repos in my local machine.
Each time I trigger index, sourcegraph app only discovers 14-15 repos.
So is there any limit local repos sourcegraph app can handle?

**Comment by emidoots** [comment]
Hello! Sorry for the late reply; there is no limit on local repos. It should pick up any in the folder you run it in.

Can you try [upgrading to the latest version](https://docs.sourcegraph.com/app#upgrading) and then clicking the profile picture => setup wizard?

<img width="325" alt="image" src="https://user-images.githubusercontent.com/3173176/225768259-13be3722-62af-4c81-b8e5-98f961ab162c.png">

From there you can select more directories/repos to include.

**Comment by haunt98** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/5424272/225966730-99599e65-9653-40f1-8ba9-f943a4bab244.png">

Somehow I don't see `Setup wizard`, do I need to clear cache or something?

**Comment by emidoots** [comment]
Apologies again for the delayed response, we were deep in working on the app until the big release today 😅 

We made a few improvements and bug fixes here very recently, and I think it will fix the issue.

Can you try upgrading one more time, using [these instructions](https://github.com/sourcegraph/sourcegraph/blob/5b035a15ef9060798bd95d356ba9791a1124bd9c/doc/app/index.md#upgrading)?

**Comment by haunt98** [comment]
Thanks @slimsag, after download latest apps. Everything is worked now!
