### ISSUE TITLE
App got stuck during stopping the session

### ISSUE THREAD

**Issue by piroskadar** [sourcegraph/app#10]
The app was open for a while and when I clicked the button "Stop" it started the killing process but remained in it and kept showing the spinning icon. The log showed that it started the process but nothing more (and it shows "Starting Sourcegraph", but it was actually stopping it). (Closed the app from op system)

<img width="649" alt="Screenshot 2023-04-06 at 10 39 04" src="https://user-images.githubusercontent.com/8168466/230343384-bfb6afe3-cd76-4389-8e2d-c5db38346a8f.png">

**Comment by emidoots** [comment]
Thank you for reporting this, we're working on a version that won't suffer from this issue.

**Comment by emidoots** [comment]
We have a new Cody app that is much, much better: https://sourcegraph.com/get-cody
