### ISSUE TITLE
Cannot upload scip-clang index

### ISSUE THREAD

**Issue by jwmcglynn** [sourcegraph/app#14]
I'm using scip-clang v0.1.1, and I upload my index like so: 

```
$ src code-intel upload -file=index.scip
💡 Inferred arguments
   repo: <snip>
   commit: <snip>
   root: 
   file: index.scip
   indexer: scip-clang
   indexerVersion: 0.1.1
   
✅ Index compressed
💡 Indexed compressed (94.89MB -> 10.80MB).
✅ Index uploaded
💡 View processing status at http://127.0.0.1:3080/github.com/<snip>/-/code-intelligence/uploads/TFNJRlVwbG9hZDoxNQ==
```

When clicking the link, I see the following reported on the status page, a few seconds after processing starts it fails with an `Gzip.NewReader: EOF` error.
<img width="957" alt="image" src="https://github.com/sourcegraph/app/assets/103489/8efbd7e2-7021-42d7-b985-7c3a1422fd47">

There's the following message in the logs:
```
[0m1684395073410103000	WARN	precise-code-intel-worker.Handle	workerutil/worker.go:412	github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker[...]).handle	Marked record as errored	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "<snip>"}, "TraceId": "6877a55c876bedd67e98d05bff1d8b1e", "SpanId": "81452836c4908b4f", "Attributes": {"error": "gzip.NewReader: EOF"}}
1684395073410153000	ERROR	precise-code-intel-worker.Handle	workerutil/worker.go:380	github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker[...]).handle.func1	operation.error	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "<snip>"}, "TraceId": "6877a55c876bedd67e98d05bff1d8b1e", "SpanId": "81452836c4908b4f", "Attributes": {"count": 1, "elapsed": 0.0815395, "error": "gzip.NewReader: EOF"}}
t=2023-05-18T07:39:36+0000 lvl=eror msg="ui HTTP handler error response" method=GET request_uri="/github.com/<snip>/-/code-graph/indexes/UHJlY2lzZUluZGV4OiJVOjE1Ig==" status_code=404 error="route not found" error_id=KrWoWt trace=
```

**Comment by emidoots** [comment]
thanks for reporting; we're working on a new version of the app which I believe will fix this issue

**Comment by jwmcglynn** [comment]
Thanks @slimsag.  What's the channel to watch for updates?  It looks like the download page only says "latest" and there doesn't appear to be autoupdate functionality.

**Comment by emidoots** [comment]
@jwmcglynn sorry for the delay in getting back to you - we've been hard at work redesigning the app. We have removed code search functionality, and instead made the app focused around our Cody AI assistant.

You can try the new version here: https://sourcegraph.com/get-cody

I'd be keen to get your feedback on this!
