### ISSUE TITLE
Documentation link yields a blank page

### ISSUE THREAD

**Issue by larstvei** [sourcegraph/app#24]
Clicking the documentation link under Cody Settings -> Embedding policies:

<img width="1912" alt="Screenshot 2023-06-30 at 01 57 38" src="https://github.com/sourcegraph/app/assets/2478638/b6d3b383-ffa0-45ad-b9bd-f4ba91a6b24b">

Gives a blank page:

<img width="1912" alt="Screenshot 2023-06-30 at 01 57 47" src="https://github.com/sourcegraph/app/assets/2478638/31e8b895-7985-4608-909f-e0bc7b54ed66">

I would expect it to open a browser, or display some documentation.

**Comment by chwarwick** [comment]
@larstvei  Thanks for reporting this issue, this will be resolved in the next update.
