### ISSUE TITLE
App fails to start due to port conflicts on deep link plugin

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/app#27]
user reported app fails to start on WSL2 (Ubuntu 22.04)

```
Could not determine the accessibility bus address
thread '<unnamed>' panicked at 'Can't create listener: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', /root/.asdf/installs/rust/1.68.0/git/checkouts/tauri-plugin-deep-link-808c2311cf9cd633/1cad838/src/linux.rs:94:49
Aborted
```

**Comment by emidoots** [comment]
We just released [a new version](https://github.com/sourcegraph/sourcegraph/releases/tag/app-v2023.7.4%2B1332.fc76a9c675) which fixes the port conflict on `:9000` (changed to `:49000`) - and are working on resolving other potential port conflicts.

(unclear which port this issue is due to)

**Comment by PriNova** [comment]
I tried out the new release and it reported the same error.
In WSL, I'm logged in with user-permissions, it tries to call tauri listener at the following path "/root/.asdf/installs/rust/1.68.0/git/checkouts/tauri-plugin-deep-link-808c2311cf9cd633/1cad838/src/linux.rs:94:49" which seems to be conflicting as non-root user.


Port :9000 is not occupied by a system PID or other processes

Logged in as root it is unable to find the  'cacheDir' and 'configDir' even they exists and reports:
```Sourcegraph starting with args: ["--cacheDir", "/root/.cache/com.sourcegraph.cody", "--configDir", "/root/.local/share/com.sourcegraph.cody"]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:163:14```

**Comment by emidoots** [comment]
Hi @PriNova - I think you're facing a different issue so I have created https://github.com/sourcegraph/app/issues/36 and will respond over there :)

**Comment by PriNova** [comment]
The first issue by chwarwick is opened by my request in discord. So the second issue reported by me is a follow-up issue. Sometimes the first issue is shown, sometimes the second.

**Comment by emidoots** [comment]
Ahh my apologies @PriNova - I understand the situation now. :)

Let's continue debugging over here if you're OK with it: https://github.com/sourcegraph/app/issues/36#issuecomment-1624477419

and I'll close this one
