### ISSUE TITLE
Change PORT to a higher port, or retry with incrementing PORT

### ISSUE THREAD

**Issue by chamatt** [sourcegraph/app#30]
The app the currently using PORT 9000 which is very commonly used by other applications. Would it be possible to increase it to a much higher port that is less commonly used? In addition to that it would be great if the app could retry on a increased port if the current one fails, which would solve the problem completely (e.g. port 9000 fails, try 9001, 9002...)

```[tasklist]
### Tasks
- [ ] Change port from 9000
- [ ] Add incrementing (+1) port retry
```

Also, thank you for this great application!

**Comment by chwarwick** [comment]
@chamatt Thanks for filling this issue, we are currently working on this issue and will let you know once we have a version that resolves this behavior.

**Comment by emidoots** [comment]
We just released [a new version](https://github.com/sourcegraph/sourcegraph/releases/tag/app-v2023.7.4%2B1332.fc76a9c675) which fixes the port conflict on `:9000` (changed to `:49000`) - and are working on resolving other potential port conflicts.

Please let me know if this helps resolve the issue for you @chamatt :)
