### ISSUE TITLE
Local embeddings do not work on MacOS

### ISSUE THREAD

**Issue by thedch** [sourcegraph/app#33]
Hi,

I have tried a few different repos and tried restarting VSCode and Cody a few times, but no luck yet.

I am trying to embed a local repo and then ask questions via the VSCode extension.

I embed the repo on the Cody UI here:

<img width="1019" alt="Screenshot 2023-07-05 at 11 44 55 PM" src="https://github.com/sourcegraph/app/assets/13357734/e99e4843-e5ef-4712-a56b-c6be3ed9d0ec">

(there's no loading bar or anything -- not clear if the embeddings are actually finished?)

And then when I go to the VSCode chat window, it says there's no embeddings. 

<img width="562" alt="Screenshot 2023-07-05 at 11 45 11 PM" src="https://github.com/sourcegraph/app/assets/13357734/82b1889b-bea6-4585-98ef-dadadab146fb">

Any help appreciated, thanks!

Cody 

```
Version 2023.7.4+1332.fc76a9c675 (20230704.202956)
```

VS Code: 

```
Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (3 wks ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by danielmarquespt** [comment]
Whats the status of the embeddings jobs?

(Advanced settings => Embeddings Jobs)

**Comment by thedch** [comment]
@danielmarquespt Looks like they list as completed, and the VS Code UI now shows successful as well! Slightly strange, I've tried a few different repos over a few days, and had never seen it working. Thanks! I'll open a new issue if I see anything else
