### ISSUE TITLE
search results didn't match query

### ISSUE THREAD

**Issue by rogpeppe** [sourcegraph/app#7]
Here's a result of a search query I made:

![image](https://user-images.githubusercontent.com/66491/229516136-3feebaa0-2f82-4d55-a970-10ff0e86487d.png)

The query was `context:global *new(T)` but the result it's showing is a previous search result. Not to mention that it's saying it's found 4 results but is only showing one.

**Comment by emidoots** [comment]
Thanks, this is very concerning & we're looking into it as our top priority.

At the same time, we're having trouble reproducing this - so if anyone sees similar behavior or can reproduce it we'd be very interested in hearing about it!

**Comment by sqs** [comment]
Also very strange that it's showing a diff result given that no `type:diff` is present in the query.

**Comment by rogpeppe** [comment]
I've seen similar issues today but can't reproduce reliably, I'm afraid.
It manifested in a similar way - an inappropriate result from a previous query.
