### ISSUE TITLE
structural search does not seem to work

### ISSUE THREAD

**Issue by rogpeppe** [sourcegraph/app#8]
When I click the "enable structural search" button to the right of the search bar, I don't see any results, despite seeing knowing there are such results in the code base.

An example:

![image](https://user-images.githubusercontent.com/66491/229517449-9e24a647-605f-41fe-a60c-9f9e039a8c3d.png)

**Comment by emidoots** [comment]
Thanks for reporting this; Structural search depends on the `comby` CLI being present on your PATH currently; you can install it from https://comby.dev/ and then it would work assuming your are not using the macOS app bundle (e.g. using homebrew or the zip file)

We will definitely improve this situation, though, I 100% agree the out-of-the-box experience here looks very broken.

**Comment by rogpeppe** [comment]
That fixed it for me, thanks! Some surfacing of the error in the UI would have been helpful.

**Comment by spwilliams-hubspot** [comment]
I've got `comby` installed (via homebrew, on MacOS), and I'm using the homebrew tap for the sourcegraph app, and I get this error any time I try to run a structural search:

```
t=2023-04-10T14:33:10+0000 lvl=eror msg="failed to execute comby command" error="Uncaught exception:\n  \n  (Failure \"Not supported\")\n\nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\nCalled from Pipeline.run in file \"lib/app/pipeline/pipeline.ml\", line 365, characters 37-91\nCalled from Dune__exe__Main.base_command_parameters.(fun) in file \"src/main.ml\", line 268, characters 6-32\nCalled from Core_kernel__Command.For_unix.run.(fun) in file \"src/command.ml\", line 2453, characters 8-238\nCalled from Base__Exn.handle_uncaught_aux in file \"src/exn.ml\", line 111, characters 6-10\n"
```
