### ISSUE TITLE
Returned (very) stale results, not the results of a new query

### ISSUE THREAD

**Issue by paul-chambers** [sourcegraph/app#9]
I entered a query:

"context:global repo:^processNewFiles$ select:symbol.struct tFSnode"

The results returned were of a query I did yesterday, on a different repo, looking for the string "SENDMAIL"

Sourcegraph app has been running continuously (inside a Ubuntu VM) for the entire time period.

**Comment by emidoots** [comment]
We've removed code search functionality from the app and released a new Cody app instead: https://sourcegraph.com/get-cody
